= Working with Jumpstarter

Not only can Jumpstarter help automated hardware testing in CI pipelines, as your project grows, Jumpstarter's remote access capabilities enable your team to share limited hardware devices across geographically distributed teams in a secure, controlled, and efficient manner.

Jumpstarter manages remote access to exporters using **Leases** which provide a specific **Client** access to an **Exporter** for a specified period of time. When a lease is created, the **Jumpstarter Service** will attempt to find a matching Exporter using the specified label selectors. Once a lease is acquired, the Client can start a session within that lease to access the hardware remotely.

Your Dev Space is already configured with credentials to access a Jumpstarter Service running in the same cluster with multiple Exporters available to lease. To list the available  Exporters, run:

[,console]
----
$ jmp get exporters
----

Each Exporter has a set of labels, these labels can be used to select the a specific group of exporters when requesting a lease. For example, you could specify a label for the architecture and then select the correct device with an `arch=aarch64`.

[#jmpexporterlease]
== Lease and interact with a remote exporter

To lease an Exporter with the Jumpstarter CLI, run:

[,console]
----
$ jmp shell --selector type=virtual
----

NOTE: This `jmp shell` command uses the default client config file located at `~/.config/jumpstarter/clients/lab.yaml`. The default client will then use the `--selector` parameter to find an exporter that matches the label `type=virtual`.

TIP: Notice that you shell prompt have been changed to `jumpstarter ⚡remote ➤`, this is to remind you that you are inside a remote Jumpstarter shell session.

When you lease an Exporter, you get exclusive access to the hardware interfaces connected to the Exporter for the duration of the lease.

To see the list of hardware interfaces exposed on the Exporter we've leased, run the `j` command without parameters:

[,console]
----
jumpstarter ⚡remote ➤ j
----

You should see an output like this:

[source,text]
----
Usage: j [OPTIONS] COMMAND [ARGS]...

  Generic composite device

Options:
  --help  Show this message and exit.

Commands:
  console  Serial port client
  flasher  Generic flasher interface
  power    Generic power
  qemu     Generic composite device
----

As this remote exporter is connected to our virtual QEMU hardware, we can use these subcommands to interact with that virtual device. We can control the power using the `power` subcommand, flash a new image with the `flasher`, or access the serial console using `console`. A physical device using a similar interface could be interacted with in the same manner.

[TIP]
====
Notice that the same top-level commands `console`, `flasher`, and `power` are also available under the `qemu` subcommand. This is because they are aliases to the same commands under `qemu` for easier access. The `ref` field in the Exporter config allows us to define aliases to other nested drivers.

.exporter config
[source,yaml]
----
# ...
export:
  console:
    ref: qemu.console
  flasher:
    ref: qemu.flasher
  power:
    ref: qemu.power
  qemu:
    type: jumpstarter_driver_qemu.driver.Qemu
    config:
      # ...
----
====

=== First boot

In previous modules, we built a RHIVOS image with our application. Now, we can use Jumpstarter to flash that image to our virtual device, boot it up, and take our first steps in testing our application remotely.

To flash the RHIVOS image we built earlier, run:

[,console]
----
jumpstarter ⚡remote ➤ ./scripts/flash-prebuilt
----

NOTE: the `./scripts/flash-prebuilt` helper script flashes a prebuilt RHIVOS image to the virtual device.

After flashing, to boot the device and view the boot messages via the serial console, run:

[,console]
----
jumpstarter ⚡remote ➤ j power on && j console start-console
----

You should be dropped into a serial console with the boot messages showing up. Once the image has finished booting, you will be presented with a login prompt. You can login with the following credentials:

[username,console]
----
root
----

[password,console]
----
password
----

After logging into the system, you can launch the installed `radio-client`:

[NOTE]
====
The `radio-service` is already running in the background as a daemon started on boot.
====

[,console]
----
$ radio-client
----

Now we can control our `radio-service` as we did when we initially built and tested the application.

[TIP]
====
Press `+` or `-` to adjust the volume, `<SPACE>` to switch stations, and `<ESC>` to pause or resume the radio.
====

When you are done with testing, press `q` to quit `radio-client`. Then exit the serial console by pressing `Ctrl+B` 3 times, this will drop you back into the Jumpstarter shell session.

=== Bridging the gap

Sometimes your tests cannot be executed directly on the target device or the Exporter host. For example, you may need to use a proprietary GUI client or service to control your application. To support these use cases, Jumpstarter implements port forwarding, which allows you to interact with services running inside the target device from your local machine as if they are running locally.

To forward a remote service port such as the `radio-service` to a local port, run the following command from within your remote Jumpstarter shell session:

[,console]
----
jumpstarter ⚡remote ➤ j radio start-portforward 9000
----

This command will forward the remote `radio` port preconfigured in the exporter config to `localhost:8000` on your local machine. Once port forwarding is started, you can run `radio-client` from your local environment and interact with the `radio-service` running on the remote device.

To stop the port forwarding, simply exit the shell with `Ctrl+D`.

Now we are finished with manual testing, exit the Jumpstarter shell session by pressing `Ctrl+D` again.

[#jmptestingpytest]
== Testing on remote exporter with Pytest

While connecting to a Jumpstarter Exporter remotely to execute our tests is already a huge step forward from the traditional ways of hardware testing, by combining the Jumpstater Python API with the pytest unit test framework, we can further improve our test process to be more automated and reliable.

TIP: You can use any testing framework with Jumpstarter, not only pytest. But we recommend pytest due to its simplicity and popularity.

An example pytest script using Jumpstarter would look like this:

.basic_test.py
[source,python]
----
from jumpstarter_testing import JumpstarterTest
import pytest

class TestRHIVOS(JumpstarterTest):
    @pytest.fixture(autouse=True, scope="session")
    def prepare(self, dut):
        dut.power.off()
        dut.flasher.flash("simple.qcow2")
        dut.power.on()

    def test_kernel_version(self, dut):
        with dut.shell() as shell:
          assert shell.run("uname -r").stdout.strip().startswith("6.11.4")

    def test_radio_client_installed(self, dut):
        with dut.shell() as shell:
          assert shell.run("which radio-client").stdout.strip() == "/usr/bin/radio-client"
----

Let's explore the script line by line.

.import
[source,python]
----
from jumpstarter_testing import JumpstarterTest
import pytest
----

The first part are the import statements, saying that we would be using the `JumpstarterTest` helper from the `jumpstarter_testing` package, as well as the `pytest` package.

.setup
[source,python]
----
class TestRHIVOS(JumpstarterTest):
    @pytest.fixture(autouse=True, scope="session")
    def prepare(self, dut):
        dut.power.off()
        dut.flasher.flash("simple.qcow2")
        dut.power.on()
----

The second part is how we set up the device under test for the remainder of the tests. So we base our test `TestRHIVOS` on the `JumpstarterTest` helper class, which provides the required logics for connecting to our Exporter. Then we have a `prepare` fixture that is auto used, which means it would be automatically executed before the test cases, and session scoped, which means it would only be executed once per test session, since we don't have to reflash our device under test in-between test cases.

TIP: In testing, a fixture provides a defined, reliable and consistent context for the tests. This could include environment (for example a database configured with known parameters) or content (such as a dataset), and in our case, a device with a given disk image flashed and booted up.

.cases
[source,python]
----
    def test_kernel_version(self, dut):
        with dut.shell() as shell:
          assert shell.run("uname -r").stdout.strip().startswith("6.11.4")

    def test_radio_client_installed(self, dut):
        with dut.shell() as shell:
          assert shell.run("which radio-client").stdout.strip() == "/usr/bin/radio-client"
----

And finally, the test cases, here we only have two test cases, one is `test_kernel_version`, which executes the `uname` command and checks if the kernel version matches our desired version of `6.11.4`, another is `test_radio_client_installed`, which checks if `radio-client` is properly installed in the image at our desired location.

To lease another Exporter and execute our test cased on it, run:

[source,bash]
----
jmp shell --selector type=virtual -- pytest basic_test.py
----
