= Running Jumpstarter an Exporter Locally

In the last module, we configured our *Exporter* with some *Drivers*. Now we can run it locally and interact with the *Drivers* through the local Jumpstarter *Client*. To start the exporter for local access, run the following command:

[,console]
----
$ jmp shell --exporter-config ./demo-exporter.yaml
----

TIP: Notice that your shell prompt now shows: `jumpstarter ⚡local ➤`. This is to remind you that you are inside a local Jumpstarter shell session.

Inside a Jumpstarter shell session, the environment variable `JUMPSTARTER_HOST` is set, pointing to a unix domain socket which the Exporter is listening on. The Jumpstarter *Client* reads this environment variable, connects to the *Exporter*, and sends requests to control the hardware interfaces, e.g. turning the power switch on.

To check the contents of your current `JUMPSTARTER_HOST` variable, you can run the following command within the Jumpstarter shell:

[,console]
----
jumpstarter ⚡local ➤ echo $JUMPSTARTER_HOST
----

== Using the `j` Command

The simplest way to interact with Jumpstarter Exporters is through the Command Line Interfaces available through the "magic" `j` command. The `j` command is only available in a Jumpstarter shell session, and is dynamically constructed reflecting the tree of Drivers configured on the currently connected Exporter.

NOTE: Not all Drivers have defined Command Line Interfaces, if a driver class does not define a CLI, commands will not be available within the `j` command.

Run the `j` command without any arguments to see the available Driver commands:

[,console]
----
jumpstarter ⚡local ➤ j
----

With the exporter config defined in `exporter-demo.yaml`, we should see an output like this:

[source,text]
----
Usage: j [OPTIONS] COMMAND [ARGS]...

  Generic composite device

Options:
  --help  Show this message and exit.

Commands:
  console  Serial port client
  flasher  Generic flasher interface
  power    Generic power
----

TIP: The name of the subcommands matches the alias we gave to the Driver instances in the Exporter config.

Run the `j power` command to see its usage:

[,console]
----
jumpstarter ⚡local ➤ j power
----

With the `MockPower` Driver, we should see an output like this:

[source,text]
----
Usage: j power [OPTIONS] COMMAND [ARGS]...

  Generic power

Options:
  --help  Show this message and exit.

Commands:
  cycle  Power cycle
  off    Power off
  on     Power on
----

This indicates that the `MockPower` Driver provides three methods, `power on`, `power off`, or `power cycle` for our mock power controller.

Try turning the power of the device under test on and off

[,console]
----
jumpstarter ⚡local ➤ j power on
jumpstarter ⚡local ➤ j power off
----

TIP: Since we are using a mock power driver nothing will happen, but if we configured it with a real power driver, e.g. a USB power relay, you would see the device being turned on and off.

== Using The Python API (Optional)

Another way to interact with Jumpstarter Exporters is through the Python API. The Jumpstarter Python API is more powerful than the `j` command as it offers the full functionalities of the Drivers, however, it also requires experience with Python scripting to use.

To use the Python API, let's write a simple Python script:

.power-control.py
[source,python]
----
from jumpstarter.common.utils import env

with env() as dut:
    print(dut.power.on())
    print(dut.power.off())
----

TIP: We are using the `with` keyword as the `env()` function returns a context manager. This allows Jumpstarter to setup and teardown connections to the Exporter gracefully.

In this example, the `env` helper method reads the `JUMPSTARTER_HOST` environment variable, connects to the Exporter, requests a list of configured drivers, and the constructs a "magic" client object mirroring the tree of Drivers exposed by the Exporter.

When we call the methods on the client object, commands are sent to the Exporter drivers similar to the `j` command. To see what methods are available in the Python API of each Driver, see https://docs.jumpstarter.dev/main/api-reference/drivers/index.html[Jumpstarter Driver API Reference]

We can run the Python script within our local Jumpstarter shell session to test it:

[,console]
----
jumpstarter ⚡local ➤ python power-control.py
----

== Next Steps

Now we have created our own Exporter config, tested it locally within our Dev Space, and learned about the `j` command and Python API. In the next module, we will connect to a remote exporter instance hosted within the OpenShift cluster directly from our Dev Space.