= Configuring Jumpstarter Exporter

At the core of Jumpstarter is *Exporter*, a program that exposes *hardware interfaces* on your *device under test* to a local or remote *Client*. The Exporter typically runs on a "host" system directly connected to your hardware through various test harnesses (think USB to UART adapters or JTAG connectors).

Exporter uses *Drivers* to abstract *hardware interfaces* into *software interfaces* allowing for simplified access. Drivers are written in *Python* to make use of the vast ecosystem of existing Python packages. While Jumpstarter comes with Drivers for many basic interfaces, custom Drivers can also be developed for specialized hardware/interfaces or to provide domain-specific abstractions for your use case.

== List Available Drivers
To list the Drivers available in your Jumpstarter installation, run the following command:

[,console]
----
$ jmp driver list
----

[TIP]
====
Some driver packages provide mock drivers, usually with a `Mock` prefix. While mock drivers do not provide access to physical or virtual hardware, they are useful for testing or demonstration.
====

== Writing Jumpstarter Exporter Config

Jumpstarter Exporter can be configured with a yaml-based config file consisting of multiple parts.

.header
[source,yaml]
----
apiVersion: jumpstarter.dev/v1alpha1
kind: ExporterConfig
----

The first part is the header, which denotes the version and kind of the config, so future versions of Jumpstarter can still be compatible with old configs.

.metadata
[source,yaml]
----
metadata:
  namespace: default
  name: demo
----

The second part is the metadata, for distinguishing between multiple exporter configs.

.connection info
[source,yaml]
----
endpoint: ""
token: ""
----

The third part is the connection info, to connect the Exporter to the Jumpstarter Service for remote access. Since we would only be using this Exporter for local access, they can be left empty.

.export
[source,yaml]
----
export:
  power:
    # provides power management: power on/off/cycle
    type: jumpstarter_driver_power.driver.MockPower
  console:
    # provides serial console access
    type: jumpstarter_driver_pyserial.driver.PySerial
    config:
      url: "loop://"
  flasher:
    # provides storage access: like flashing a disk image into a sdcard
    type: jumpstarter_driver_opendal.driver.MockFlasher
----

The last and most important part is export, which is a tree of Drivers to be exported to the Client. Here we've configured three Drivers, `power`, `console` and `flasher`. Drivers can be specified with its full Python import path, and be configured with additional parameters, e.g. we configured the `PySerial` Driver to connect to the `loop://` serial port, which is a virtual serial port that echos everything sent to it.

To see what config options are available on each Driver, check https://docs.jumpstarter.dev/main/api-reference/drivers/index.html[Jumpstarter Driver API Reference]
