= {lab_name}

image::jumpstarter.svg[jumpstarter,200,100]

The move to software-defined vehicles (SDVs) in the automotive industry presents challenges in developing software for electronic control units (ECUs) that require hardware-in-the-loop (HIL) testing.

Project Jumpstarter is an open source framework for cloud-native HIL testing of automotive ECUs and edge devices. Integrated with development tools such as Red Hat Developer Hub and OpenShift Pipelines, it supports DevSecOps practices, including automation and infrastructure as code.

This session will highlight Jumpstarter's role in

* Scaling cloud-native HIL testing for distributed teams
* Automating ECU test scenarios in CI/CD workflows
* Delivering infrastructure-as-code for hardware environments

Real-world examples and demos will illustrate how Jumpstarter accelerates development, improves quality assurance, and enhances collaboration.

== Objectives

* Learn how to use a "Software Factory" for the development of automotive software, including hardware-in-the-loop (HIL) testing and validation.
* Learn how to use a cloud based development environment and CI/CD pipelines to test software on physical and virtual hardware.
* Understand how to build a custom Red Hat In-Vehicle OS (RHIVOS) image and use "Jumpstarter" to deploy it onto an automotive development board (SoC).
* Understand how to onboard and configure new hardware or devices into Jumpstarter.

=== Lab structure

This lab consists of 3 modules.

* Module 1: Introduction to  Automotive Development Platform and "Project Jumpstarter" (15min)

* Module 2: Build a simple automotive application (30min)

* Module 3: Test and automate with HIL (45 min)

=== Lab Access

The lab can be accesses through Red Hat Developer Hub, you can login with the credentials printed on the sticker attached to your laptop.

{devhub_url}
