= Lab Overview

Welcome to the *{lab_name}*!

image::jumpstarter.svg[width=512px]

== About this lab

The move to software-defined vehicles (SDVs) in the automotive industry presents challenges in developing software for electronic control units (ECUs) that 
require hardware-in-the-loop (HIL) testing.

This lab provides you with an integrated development environment that teaches you how to use a "Software Factory" approach for the 
development of automotive software. You will learn how to develop, build and test automotive software 
in https://developers.redhat.com/rhdh/overview[Red Hat Developer Hub] and how to build a 
custom https://www.redhat.com/en/blog/new-standard-red-hat-vehicle-operating-system-modern-and-future-vehicles[Red Hat In-Vehicle OS (RHIVOS)] image with 
containerized automotive application embedded. 

You will also learn how to use https://jumpstarter.dev/[Jumpstarter] for cloud-native hardware-in-the-loop (HIL) testing 
of automotive ECUs and edge devices, and how it integrates with https://developers.redhat.com/products/openshift-dev-spaces/overview[Red Hat OpenShift Dev Spaces] 
and https://www.redhat.com/en/technologies/cloud-computing/openshift/pipelines[Red Hat OpenShift Pipelines] to enable DevSecOps practices, 
including automation, continuous integration, and infrastructure as code.

* describe what the lab is about

* describe the underlying concepts
** What is a "Software Factory"?
** What is Hardware-in-the-Loop (HIL) testing?
** Overview of the Automotive Development Platform architecture
** Overview of the Jumpstarter architecture