= Introduction to the Lab

The move to software-defined vehicles (SDVs) in the automotive industry presents challenges in developing software for electronic control units (ECUs) that 
require hardware-in-the-loop (HIL) testing.

This lab provides you with an integrated development environment that teaches you how to use a "Software Factory" approach for the 
development of automotive software. You will learn how to develop, build and test automotive software 
in https://developers.redhat.com/rhdh/overview[Red Hat Developer Hub] and how to build a 
custom https://www.redhat.com/en/blog/new-standard-red-hat-vehicle-operating-system-modern-and-future-vehicles[Red Hat In-Vehicle OS (RHIVOS)] image with 
containerized a automotive application embedded. 

Additionally, you’ll explore https://jumpstarter.dev/[Jumpstarter] for cloud-native HIL testing of ECUs and edge devices. 
You'll learn how it integrates with https://developers.redhat.com/products/openshift-dev-spaces/overview[Red Hat OpenShift Dev Spaces]  and 
https://www.redhat.com/en/technologies/cloud-computing/openshift/pipelines[Red Hat OpenShift Pipelines] to enable DevSecOps practices, 
such as automation, continuous integration, and infrastructure as code.

== Lab activities and objectives

In this lab, you will follow a typical development workflow for automotive software:

* Create a new application project from a Red Hat Developer Hub template
* Develop and test the application in Red Hat Dev Spaces
* Build a new Red Hat In-Vehicle OS (RHIVOS) image with the application and test it on a virtual machine
* Use Jumpstarter to test the application interactively

At the end of this lab, you will have a basic understanding of the Red Hat Automotive Development Platform and how to use it to develop, build, and test automotive software.

== Next

Before diving into the lab activities, let's take a look at the Red Hat Automotive Development Platform and Jumpstarter.
