= Build RHIVOS Image With Application

In this module we will learn how to build a simple automotive application, package it into a container, and embed the containerized application in an RHIVOS image.

[#application]
== Build A Simple Automotive Application

The source repo contains a set of applications that demonstrate how typical automotive applications use SOME/IP to talk to each other, these apps work both natively and in a container. For the purpose of this lab, we would be focusing on `radio-service`, This is a service that emulates a radio, regularly publishing information about the current song, radio station and volume. It accepts requests to turn on/off, switch channel, and change volume.

To build the applications, run the following commands in the Dev Space terminal:

[source,bash]
----
cmake .
make
----

Then start `radio-service` in the backgroud and interact with it using `radio-client`:

[source,bash]
----
./radio-service &
./radio-client
----

Press `+` or `-` to adjust the volume, `<SPACE>` to switch station, `<ESC>` to pause or resume, and `q` to quit the client. And finally stop `radio-service` when you are done testing:

[source,bash]
----
pkill radio-service
----

Feel free to make modification to `radio-stations.cpp` adding songs or stations, and repeat the build test cycle. When you are done, commit all the changes, create a new tag, and push the changes:

[source,bash]
----
git commit -a -m "first revision"
git tag v0.0.1
git push
git push --tags
----

A GitLab CI task would be triggered to build the applications into a container, and push the container into a registry. You can check the build process here:

{app_build_pipeline}

[#rhivos]
== Build RHIVOS Image

=== RHIVOS

https://www.redhat.com/en/blog/new-standard-red-hat-vehicle-operating-system-modern-and-future-vehicles[RHIVOS], short for Red Hat In-Vehicle Operating System, is an extension to Red Hat Enterprise Linux, the world’s leading enterprise Linux platform. It can help enable and accelerate many of the current trends in the automotive space in ways that traditional proprietary systems cannot, moving the auto industry into a more scalable way of design.

=== Automotive Image Builder

To build RHIVOS images, we would be using https://gitlab.com/CentOS/automotive/src/automotive-image-builder[automotive image builder], a tool to create various kinds of OS images based on CentOS derived distributions. The main tool is called `automotive-image-builder`, and the basic operation it does is called "composing" manifests. The compose operation takes a yaml-based automotive image manifest, as well as a set of options affecting the compose and resolves the manifest into an osbuild json file. This json file is a precise build instruction for how to build an image with osbuild with the very specific software that was chosen during the compose. For example, the version of selected packages and container images is chosen during the compose.

=== Automotive Image Builder Manifests

The source repo is already populated with some automotive image builder manifests for RHIVOS. From the file explorer of the Dev Space, open `manifests/simple.aib.yml`, which is an example showing how to build a minimal RHIVOS image with additional rpm packages and root password preset. Another noteworthy file is `.aib-ci.yml`, which specifies the base image to use, target architecture and board, and other parameters to be passed to `automotive-image-builder`

=== Build RHIVOS image with Automotive Image Builder

Automotive image builder does not support cross-compilation, to build images for other architectures (like aarch64), we must run it on the respective systems. A aarch64 base virtual machine is provisioned as part of the lab to serve as our builder host. A helper script is provided to execute the build on it, in the Dev Space terminal, run:

[source,bash]
----
aib-build qemu simple.qcow2
----

NOTE: We are using the `qemu` preset in `.aib-ci.yaml` to build an image targeting the qemu platform, and store the resulting image as `simple.qcow2`

A GitLab CI task was also triggered to build the RHIVOS image with the application container embeded. You can check the build process here:

{os_build_pipeline}
