= Environment Setup

[#rhdh]
== Red Hat Developer Hub

https://developers.redhat.com/rhdh/overview[Red Hat Developer Hub] is an enterprise-grade Internal Developer Portal, combined with Red Hat OpenShift, Red Hat Developer Hub allows platform engineering teams to offer software templates, pre-architected and supported approaches to maximize developer skills, ease onboarding, and increase development productivity, and focus on writing great code by reducing friction and frustration for development teams.

[#rhods]
== Red Hat OpenShift Dev Spaces

Built on the open source Eclipse Che project, https://developers.redhat.com/products/openshift-dev-spaces/overview[Red Hat OpenShift Dev Spaces] uses Kubernetes and containers to provide developers and other IT team members with a consistent, secure, and zero-configuration development environment. The experience is as fast and familiar as an integrated development environment (IDE) on your laptop.

[#setup]
== Create Development Environment with Red Hat Developer Hub

We will be using Red Hat Developer Hub to setup the development environment for our lab. To get started, navigate to

{rhdh_url}

and sign in with GitLab

TIP: Your username is `{username}`, and password is `{password}`

. Navigate to "Create" tab on the side bar
. Choose the "Jumpstarter" template
. Leave the forms as default for the "Provide Project Information", "Source Code Repository and Container Registry Information" and "Provide Cluster Information" screen, click "Next"
. Click "Create" on the "Review" screen

Our source code repository for RHIVOS image manifests and a Dev Space should be created in a few seconds, click "Open Component in catalog" to get to the dashboard for our development environment. Then click "OpenShift DevSpaces (VS Code)" to enter the Dev Space and log in with rhsso.

TIP: Your username is `{username}`, and password is `{password}`

The Dev Space initialization can take a while, but you will soon be dropped into a VS Code based web IDE. When prompted with whether you trust the authors, click yes.

== Recap
In this module, with the help of Red Hat Developer Hub, we've created a source code repo for the RHIVOS image manifests, and a Dev Space web IDE connected to the repo.
