= Testing On Remote Jumpstarter Exporter With Pytest

While connecting to a Jumpstarter Exporter remotely to execute our tests is already a huge step forward from the traditional ways of hardware testing, by combining the Jumpstater Python API with the pytest unit test framework, we can further improve our test process to be more automated and reliable.

TIP: You can use any testing framework with Jumpstarter, not only pytest. But we recommend pytest due to its simplicity and popularity.

An example pytest script using Jumpstarter would look like this:

.basic_test.py
[source,python]
----
from jumpstarter_testing import JumpstarterTest
import pytest

class TestRHIVOS(JumpstarterTest):
    @pytest.fixture(autouse=True, scope="session")
    def prepare(self, dut):
        dut.power.off()
        dut.flasher.flash("simple.qcow2")
        dut.power.on()

    def test_kernel_version(self, dut):
        with dut.shell() as shell:
          assert shell.run("uname -r").stdout.strip().startswith("6.11.4")

    def test_radio_client_installed(self, dut):
        with dut.shell() as shell:
          assert shell.run("which radio-client").stdout.strip() == "/usr/bin/radio-client"
----

Let's explore the script line by line.

.import
[source,python]
----
from jumpstarter_testing import JumpstarterTest
import pytest
----

The first part are the import statements, saying that we would be using the `JumpstarterTest` helper from the `jumpstarter_testing` package, as well as the `pytest` package.

.setup
[source,python]
----
class TestRHIVOS(JumpstarterTest):
    @pytest.fixture(autouse=True, scope="session")
    def prepare(self, dut):
        dut.power.off()
        dut.flasher.flash("simple.qcow2")
        dut.power.on()
----

The second part is how we set up the device under test for the remainder of the tests. So we base our test `TestRHIVOS` on the `JumpstarterTest` helper class, which provides the required logics for connecting to our Exporter. Then we have a `prepare` fixture that is auto used, which means it would be automatically executed before the test cases, and session scoped, which means it would only be executed once per test session, since we don't have to reflash our device under test in-between test cases.

TIP: In testing, a fixture provides a defined, reliable and consistent context for the tests. This could include environment (for example a database configured with known parameters) or content (such as a dataset), and in our case, a device with a given disk image flashed and booted up.

.cases
[source,python]
----
    def test_kernel_version(self, dut):
        with dut.shell() as shell:
          assert shell.run("uname -r").stdout.strip().startswith("6.11.4")

    def test_radio_client_installed(self, dut):
        with dut.shell() as shell:
          assert shell.run("which radio-client").stdout.strip() == "/usr/bin/radio-client"
----

And finally, the test cases, here we only have two test cases, one is `test_kernel_version`, which executes the `uname` command and checks if the kernel version matches our desired version of `6.11.4`, another is `test_radio_client_installed`, which checks if `radio-client` is properly installed in the image at our desired location.

To lease another Exporter and execute our test cased on it, run:

[source,bash]
----
jmp shell --selector example.com/board=qemu -- pytest basic_test.py
----
