= Connecting to a Remote Jumpstarter Exporter

While Jumpstarter can help automate interactions between a developer and local hardware, this does not scale well when there are multiple developers and limited hardware is available. As your project grows, Jumpstarter's remote access capabilities enable your team to share limited hardware devices across geographically distributed teams in a secure, controlled, and efficient manner.

Jumpstarter manages remote access to exporters using **Leases** which provide a specific **Client** access to an **Exporter** for a specified period of time. When a lease is created, the **Jumpstarter Service** will attempt to find a matching Exporter using the specified label selectors. Once a lease is acquired, the Client can start a session within that lease to access the hardware remotely.

Your Dev Space is already configured with credentials to access a Jumpstarter Service running in the same cluster with multiple Exporters available to lease. To list the available  Exporters, run:

[,console]
----
$ jmp get exporters
----

Each Exporter has a set of labels, these labels can be used to select the a specific group of exporters when requesting a lease. For example, you could specify a label for the architecture and then select the correct device with an `arch=aarch64`.

== Lease and Interact with a Remote Exporter Using Jumpstarter CLI

To lease an Exporter with the Jumpstarter CLI, run:

[,console]
----
$ jmp shell --selector example.com/board=qemu
----

NOTE: This command is almost identical to the one we used to enter a local Jumpstarter shell session in the last module, however by omitting the `--exporter-config` parameter, the `jmp shell` command will instead use the default client config file located at `~/.config/jumpstarter/clients/lab.yaml`. The default client will then use the `--selector` parameter to find an exporter that matches the label `example.com/board=qemu`.

TIP: Notice that you shell prompt have been changed to `jumpstarter ⚡remote ➤`, this is to remind you that you are inside a remote Jumpstarter shell session.

When you lease an Exporter, you get exclusive access to the hardware interfaces connected to the Exporter for the duration of the lease.

To see the list of hardware interfaces exposed on the Exporter we've leased, run the `j` command without parameters:

[,console]
----
jumpstarter ⚡remote ➤ j
----

You should see an output like this:

[source,text]
----
Usage: j [OPTIONS] COMMAND [ARGS]...

  Generic composite device

Options:
  --help  Show this message and exit.

Commands:
  console  Serial port client
  flasher  Generic flasher interface
  power    Generic power
  qemu     Generic composite device
----

As this remote exporter is connected to our virtual QEMU hardware, we can use these subcommands to interact with that virtual device. We can control the power using the `power` subcommand, flash a new image with the `flasher`, or access the serial console using `console`. A physical device using a similar interface could be interacted with in the same manner.

[TIP]
====
Notice that the same top-level commands `console`, `flasher`, and `power` are also available under the `qemu` subcommand. This is because they are aliases to the same commands under `qemu` for easier access. The `ref` field in the Exporter config allows us to define aliases to other nested drivers.

.exporter config
[source,yaml]
----
# ...
export:
  console:
    ref: qemu.console
  flasher:
    ref: qemu.flasher
  power:
    ref: qemu.power
  qemu:
    type: jumpstarter_driver_qemu.driver.Qemu
    config:
      # ...
----
====

=== First Boot

In previous modules,we built a RHIVOS image with our application. Now, we can use Jumpstarter to flash that image to our virtual device, boot it up, and take our first steps in testing our application remotely.

To flash the RHIVOS image we built earlier, run:

[,console]
----
jumpstarter ⚡remote ➤ j flasher flash simple.qcow2
----

After flashing, to boot the device and view the boot messages via the serial console, run:

[,console]
----
jumpstarter ⚡remote ➤ j power on && j console start-console
----

You should be dropped into a serial console with the boot messages showing up. Once the image has finished booting, you will be presented with a login prompt. You can login with the following credentials:

[username,console]
----
jumpstarter
----

[password,console]
----
password
----

After logging into the system, you can launch the installed `radio-client`:

[NOTE]
====
The `radio-service` is already running in the background as a daemon started on boot.
====

[,console]
----
$ radio-client
----

Now we can control our `radio-service` as we did when we initially built and tested the application.

[TIP]
====
Press `+` or `-` to adjust the volume, `<SPACE>` to switch stations, and `<ESC>` to pause or resume the radio.
====

When you are done with testing, press `q` to quit `radio-client`. Then exit the serial console by pressing `Ctrl+B` 3 times, this will drop you back into the Jumpstarter shell session.

=== Bridging The Gap

Sometimes your tests cannot be executed directly on the target device or the Exporter host. For example, you may need to use a proprietary GUI client or service to control your application. To support these use cases, Jumpstarter implements port forwarding, which allows you to interact with services running inside the target device from your local machine as if they are running locally.

To forward a remote service port such as the `radio-service` to a local port, run the following command from within your remote Jumpstarter shell session:

[,console]
----
jumpstarter ⚡remote ➤ j radio start-portforward 8000
----

This command will forward the remote `radio` port preconfigured in the exporter config to `localhost:8000` on your local machine. Once port forwarding is started, you can run `radio-client` from your local environment and interact with the `radio-service` running on the remote device.

To stop the port forwarding, simply exit the shell with `Ctrl+D`.

Now we are finished with manual testing, exit the Jumpstarter shell session by pressing `Ctrl+D` again.

== Next Steps

Now that we've built our application, tested it locally, and tested the built RHIVOS image on virtual hardware, we're ready to begin testing our application automatically using CI/CD pipelines. In the next module, we'll go over the process of creating a CI/CD pipeline with OpenShift Pipelines and running automated test with Jumpstarter in CI.